# Set up in cloud

In [1]:
!gsutil -m cp -r gs://seer-models/models/issue_grouping_v1 .

Copying gs://seer-models/models/issue_grouping_v1/.DS_Store...
Copying gs://seer-models/models/issue_grouping_v1/data.pkl...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/README.md...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/config.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/1_Pooling/config.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/config_sentence_transformers.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/modules.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/sentence_bert_config.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/vocab.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/configuration_bert.py...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/special_tokens_map.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/merges.txt...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/modeling_bert.py...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/tokenizer_config.json...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/model.safetensors...
Copying gs://seer-models/models/issue_grouping_v1/embeddings/tokenizer.json...
==> NOTE: You are downloading one or more large file(s), which would
run significantly faster if you enabled sliced object downloads. This
feature is enabled by default but requires that compiled crcmod be
installed (see "gsutil help crcmod").

CommandException:
Downloading this composite object requires integrity checking with CRC32c,
but your crcmod installation isn't using the module's C extension, so the
hash computation will likely throttle download performance. For help
installing the extension, please see "gsutil help crcmod".

To download regardless of crcmod performance or to skip slow integrity
checks, see the "check_hashes" option in your boto config file.

NOTE: It is strongly recommended that you not disable integrity checks. Doing so
could allow data corruption to go undetected during uploading/downloading.
CommandException: 1 file/object could not be transferred.

In [4]:
!gsutil -m -o GSUtil:check_hashes=never cp -r gs://seer-models/models/issue_grouping_v1/embeddings/model.safetensors issue_grouping_v1/embeddings/model.safetensors

Copying gs://seer-models/models/issue_grouping_v1/embeddings/model.safetensors...
WARNING: Found no hashes to validate object downloaded to issue_grouping_v1/embeddings/model.safetensors. Integrity cannot be assured without hashes.
\ [1/1 files][613.7 MiB/613.7 MiB] 100% Done
Operation completed over 1 objects/613.7 MiB.

In [6]:
!gsutil -m -o GSUtil:check_hashes=never cp -r gs://grouping-data/final_csvs .

Copying gs://grouping-data/final_csvs/synthetic-semi-easy-negatives.csv...
Copying gs://grouping-data/final_csvs/test.csv...
Copying gs://grouping-data/final_csvs/train.csv...
Copying gs://grouping-data/final_csvs/val.csv...
WARNING: Found no hashes to validate object downloaded to ./final_csvs/val.csv. Integrity cannot be assured without hashes.
WARNING: Found no hashes to validate object downloaded to ./final_csvs/test.csv. Integrity cannot be assured without hashes.
WARNING: Found no hashes to validate object downloaded to ./final_csvs/synthetic-semi-easy-negatives.csv. Integrity cannot be assured without hashes.
WARNING: Found no hashes to validate object downloaded to ./final_csvs/train.csv. Integrity cannot be assured without hashes.

In [1]:
!pip uninstall tensorflow

WARNING: Skipping tensorflow as it is not installed.

Add a Colab secret for your `GITHUB_TOKEN`

In [ ]:
import os

os.environ["GITHUB_TOKEN"] = ""
os.environ["WANDB_API_KEY"] = ""

In [3]:
!pip install git+https://${GITHUB_TOKEN}@github.com/getsentry/grouping-trainer.git

Collecting git+https://****@github.com/getsentry/grouping-trainer.git
  Cloning https://****@github.com/getsentry/grouping-trainer.git to /tmp/pip-req-build-_de3wc_m
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/getsentry/grouping-trainer.git' /tmp/pip-req-build-_de3wc_m
  Resolved https://****@github.com/getsentry/grouping-trainer.git to commit 1914c374126a40bd66b17713ce06f2f4d05d9060
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate==1.12.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (1.12.0)
Requirement already satisfied: datasets==4.4.1 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (4.4.1)
Requirement already satisfied: optimum==1.27.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (1.27.0)
Requirement already satisfied: polars==1.33.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (1.33.0)
Requirement already satisfied: pydantic==2.11.9 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (2.11.9)
Requirement already satisfied: sentence-transformers==5.1.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (5.1.0)
Requirement already satisfied: torch==2.8.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (2.8.0+cu126)
Requirement already satisfied: torchvision==0.23.0 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (0.23.0+cu126)
Requirement already satisfied: transformers==4.56.2 in /usr/local/lib/python3.12/dist-packages (from grouping-trainer==0.1.0) (4.56.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.12.0->grouping-trainer==0.1.0) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (3.20.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets==4.4.1->grouping-trainer==0.1.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (2025.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic==2.11.9->grouping-trainer==0.1.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic==2.11.9->grouping-trainer==0.1.0) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic==2.11.9->grouping-trainer==0.1.0) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic==2.11.9->grouping-trainer==0.1.0) (0.4.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.1.0->grouping-trainer==0.1.0) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.1.0->grouping-trainer==0.1.0) (1.16.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.1.0->grouping-trainer==0.1.0) (11.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->grouping-trainer==0.1.0) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.56.2->grouping-trainer==0.1.0) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.56.2->grouping-trainer==0.1.0) (0.22.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (3.13.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.12.0->grouping-trainer==0.1.0) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==4.4.1->grouping-trainer==0.1.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==4.4.1->grouping-trainer==0.1.0) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.8.0->grouping-trainer==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.8.0->grouping-trainer==0.1.0) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.4.1->grouping-trainer==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.4.1->grouping-trainer==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.4.1->grouping-trainer==0.1.0) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers==5.1.0->grouping-trainer==0.1.0) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers==5.1.0->grouping-trainer==0.1.0) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.4.1->grouping-trainer==0.1.0) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==4.4.1->grouping-trainer==0.1.0) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets==4.4.1->grouping-trainer==0.1.0) (1.3.1)

# Set up

In [1]:
# !rm -rf output/

In [ ]:
import math

from datetime import datetime
import polars as pl
from sentence_transformers import SentenceTransformerTrainingArguments
from sentence_transformers.training_args import MultiDatasetBatchSamplers
import torch

import grouping_trainer as gt
import utils

In [2]:
timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")

In [3]:
# assert torch.cuda.is_available()

Some vars to care about

In [ ]:
SAMPLE_TRAIN: int | None = None if torch.cuda.is_available() else 30
SAMPLE_VAL: int | None = None if torch.cuda.is_available() else 20

OUTPUT_DIR = f"./{timestamp}-output"
PER_DEVICE_TRAIN_BATCH_SIZE = 1  # TODO: higher. Needed for L4
GRADIENT_ACCUMULATION_STEPS = 32  # Ideally lower. Needed for L4
PER_DEVICE_EVAL_BATCH_SIZE = 1  # TODO: higher
EVAL_STEPS = 10  # TODO: higher

# Load model

In [5]:
gt.utils._cuda_empty_cache()

In [ ]:
# model_path = "issue_grouping_v1/embeddings"
model_path = "/Users/kdubey/projects/seer/models/issue_grouping_v1/embeddings"
model = gt.utils.SentenceTransformer(str(model_path), trust_remote_code=True)
model.device

device(type='mps', index=0)

In [16]:
assert "layernorm" in repr(model[0].auto_model).lower()
assert "batch" not in repr(model[0].auto_model).lower()

Don't have batch norm. That could mess up stuff for the deduplication strategy.

In [17]:
_ = model.encode("test")

# Load data

We'll make a `dataset_val` for val loss.

In [ ]:
dataset_val = gt.train.df_to_dataset(utils.load_val_df(sample_size=SAMPLE_VAL))
len(dataset_val)

In [ ]:
dataset_dict_train, frac_positive = utils.load_train_dataset_dict(
    sample_size=SAMPLE_TRAIN, min_dataset_size=PER_DEVICE_TRAIN_BATCH_SIZE
)
len(dataset_dict_train)

  0%|          | 0/27 [00:00<?, ?it/s]

# Set up `Trainer`

In [ ]:
evaluator = gt.evaluator.MinPrecisionEvaluator(
    sentences1=list(dataset_val["query_stacktrace_string"]),
    sentences2=list(dataset_val["candidate_stacktrace_string"]),
    labels=[int(record["label"]) for record in dataset_val],
    name="val",
    show_progress_bar=True,
    batch_size=PER_DEVICE_EVAL_BATCH_SIZE,
    truncate_dims=(64, 768),
)

In [14]:
def init_bias(frac_positive: float):
    return math.log(frac_positive / (1 - frac_positive))

In [ ]:
trainer = gt.train.Trainer(
    model=model,
    args=SentenceTransformerTrainingArguments(
        # These should prolly be unchanged
        output_dir=OUTPUT_DIR,
        bf16=torch.cuda.is_bf16_supported(),
        fp16=False,
        dataloader_pin_memory=torch.cuda.is_available(),
        num_train_epochs=1,
        # Save memory
        gradient_checkpointing=True,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        #
        # Datalaoder
        multi_dataset_batch_sampler=MultiDatasetBatchSamplers.PROPORTIONAL,
        # Each iter, pick a project randomly, sample from it.
        # Next iter, pick another project randomly, sample from it, etc.
        per_device_train_batch_size=PER_DEVICE_TRAIN_BATCH_SIZE,
        seed=42,  # passed to batch sampler
        #
        # Optimizer
        learning_rate=2e-5,
        learning_rate_mapping={
            # These are important to tune. Higher so that training doesn't get stuck. TODO: check
            r"^log_scale$": 2e-4,
            r"^bias$": 2e-4,
        },
        weight_decay=0.01,
        warmup_ratio=0.1,
        #
        # Eval
        per_device_eval_batch_size=PER_DEVICE_EVAL_BATCH_SIZE,
        eval_strategy="steps",
        eval_steps=EVAL_STEPS,
        #
        # Logging
        logging_strategy="steps",
        logging_steps=EVAL_STEPS,  # train loss alongside metrics table
        run_name=f"{timestamp}-grouping-trainer",
        report_to="wandb",
        #
        # Checkpointing
        save_strategy="steps",
        save_steps=EVAL_STEPS // 5,
        save_total_limit=2,
    ),
    #
    # Training
    loss=gt.train.SigmoidPairwiseLoss(
        model,
        bias_init=init_bias(frac_positive),
        matryoshka_dims=[768, 512, 256, 128, 64],
        matryoshka_weights=[2, 1, 1, 0.5, 0.25],
        n_dims_per_step=2,
    ),
    data_collator=gt.train.DefaulDataCollator(tokenize_fn=model.tokenize),
    train_dataset=dataset_dict_train,
    shuffle_within_dataset=False,  # more cache hits in each forward
    #
    # Evaluator
    eval_dataset=dataset_val,  # val loss
    evaluator=evaluator,  # val auc, etc.
    #
    # Other
    # callbacks=[...],  # TrainerCallbacks
)

In [18]:
train_output = trainer.train()

You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Batches:   0%|          | 0/122 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Batches:   0%|          | 0/122 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Batches:   0%|          | 0/122 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

In [19]:
train_output

TrainOutput(global_step=32, training_loss=1.136501893401146, metrics={'train_runtime': 551.681, 'train_samples_per_second': 1.813, 'train_steps_per_second': 0.058, 'total_flos': 0.0, 'train_loss': 1.136501893401146, 'epoch': 1.0})

In [20]:
df_logs = pl.DataFrame(trainer.state.log_history)
df_logs
# df_logs.write_csv("training_logs.csv")

shape: (7, 22)
┌────────┬───────────┬─────────────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ loss   ┆ grad_norm ┆ learning_ra ┆ epoch ┆ … ┆ train_samp ┆ train_step ┆ total_flos ┆ train_loss │
│ ---    ┆ ---       ┆ te          ┆ ---   ┆   ┆ les_per_se ┆ s_per_seco ┆ ---        ┆ ---        │
│ f64    ┆ f64       ┆ ---         ┆ f64   ┆   ┆ cond       ┆ nd         ┆ f64        ┆ f64        │
│        ┆           ┆ f64         ┆       ┆   ┆ ---        ┆ ---        ┆            ┆            │
│        ┆           ┆             ┆       ┆   ┆ f64        ┆ f64        ┆            ┆            │
╞════════╪═══════════╪═════════════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2.0202 ┆ 11.295671 ┆ 0.000016    ┆ 0.32  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ null   ┆ null      ┆ null        ┆ 0.32  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 0.8016 ┆ 8.31354   ┆ 0.000009    ┆ 0.64  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ null   ┆ null      ┆ null        ┆ 0.64  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 0.7075 ┆ 15.062196 ┆ 0.000002    ┆ 0.96  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ null   ┆ null      ┆ null        ┆ 0.96  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ null   ┆ null      ┆ null        ┆ 1.0   ┆ … ┆ 1.813      ┆ 0.058      ┆ 0.0        ┆ 1.136502   │
└────────┴───────────┴─────────────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In case you OOM'd, consider:

In [ ]:
trainer.per_device_token_budget /= 2
trainer.train(resume_from_checkpoint=True)